# Generated by Django 3.0.12 on 2021-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('conventional_long_name', models.CharField(max_length=250, verbose_name='Официальное название')),
                ('local_long_name', models.CharField(blank=True, max_length=250, verbose_name='Официальное название на местном языке')),
                ('local_short_name', models.CharField(blank=True, max_length=250, verbose_name='Короткое название на местном языке')),
                ('capital_name', models.CharField(blank=True, max_length=250, verbose_name='Столица')),
                ('continent', models.CharField(choices=[('AF', 'Африка'), ('AS', 'Евразия'), ('EU', 'Евразия'), ('NA', 'Северная Америка'), ('SA', 'Южная Америка'), ('AU', 'Австралия'), ('NO', '')], default='NO', max_length=50, verbose_name='Континент')),
                ('anthem', models.URLField(blank=True, max_length=250, verbose_name='Гимн')),
                ('motto', models.CharField(blank=True, max_length=250, verbose_name='Девиз')),
                ('official_language', models.CharField(blank=True, max_length=50, verbose_name='Официальный язык')),
                ('national_language', models.CharField(blank=True, max_length=50, verbose_name='Национальный язык')),
                ('internet_tld', models.CharField(blank=True, max_length=10, verbose_name='Интернет-домен')),
                ('currency_name', models.CharField(blank=True, max_length=50, verbose_name='Название валюты')),
                ('currency_code', models.CharField(blank=True, max_length=3, verbose_name='Код валюты')),
                ('currency_simbol', models.CharField(blank=True, max_length=1, verbose_name='Символ валюты')),
                ('iso_code_a2', models.CharField(blank=True, max_length=2, verbose_name='ISO код (2alpha)')),
                ('iso_code_a3', models.CharField(blank=True, max_length=3, verbose_name='ISO код (3alpha)')),
                ('iso_code_num', models.CharField(blank=True, max_length=4, verbose_name='ISO код (numeric)')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
