# Generated by Django 3.0.12 on 2021-02-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20210223_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='flags', to='countries.Color', verbose_name='Цвета'),
        ),
    ]
