# Generated by Django 3.0.12 on 2021-02-24 17:32

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_auto_20210223_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='figure',
        ),
        migrations.AddField(
            model_name='flag',
            name='flag_day',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='День флага'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flag',
            name='sripes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('h', 'Горизонтальные'), ('v', 'Вертикальные'), ('d', 'Диагональные'), ('no', '')], default='no', max_length=50, verbose_name='Полосы на флаге'),
        ),
    ]
