# Generated by Django 3.0.12 on 2021-02-24 17:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_auto_20210224_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='figure',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('crescent', 'Полумесяц'), ('star', 'Звезда'), ('emblem', 'Герб'), ('animal', 'Животное'), ('bird', 'Птица'), ('crown', 'Корона'), ('weapon', 'Оружие'), ('sun', 'Солнце'), ('plant', 'Растение'), ('circle', 'Круг'), ('triangle', 'Треугольник'), ('cross', 'Крест')], max_length=50, verbose_name='Фигура на флаге'),
        ),
    ]
