# Generated by Django 3.0.12 on 2021-02-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_flag_figure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='figure',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='sripes',
        ),
        migrations.AddField(
            model_name='flag',
            name='Горизонтальные',
            field=models.BooleanField(default=False, verbose_name='Горизонтальные полосы'),
        ),
    ]
