# Generated by Django 3.0.12 on 2021-02-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_auto_20210224_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='Горизонтальные',
            new_name='has_horizontal_stripes',
        ),
    ]
