# Generated by Django 3.0.12 on 2021-02-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0013_auto_20210226_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='flag_facts',
            field=models.TextField(blank=True, verbose_name='Интересное о флаге'),
        ),
        migrations.AddField(
            model_name='flag',
            name='history_text',
            field=models.TextField(blank=True, verbose_name='История флага'),
        ),
        migrations.AddField(
            model_name='flag',
            name='usage_description',
            field=models.TextField(blank=True, verbose_name='Использование дизайна'),
        ),
    ]
