# Generated by Django 3.0.12 on 2021-02-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0014_auto_20210226_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flag',
            new_name='NationalFlag',
        ),
        migrations.AlterModelOptions(
            name='nationalflag',
            options={'verbose_name': 'Национальный флаг', 'verbose_name_plural': 'Национальные флаги'},
        ),
    ]
