# Generated by Django 3.0.12 on 2021-02-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0015_auto_20210228_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NationalFlag',
            new_name='Flag',
        ),
    ]
