# Generated by Django 3.0.12 on 2021-02-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0016_auto_20210228_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета флагов'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.CreateModel(
            name='HistoricalFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('from_year', models.PositiveSmallIntegerField(verbose_name='Год принятия')),
                ('to_year', models.PositiveSmallIntegerField(verbose_name='Год отмены')),
                ('image_url', models.URLField(max_length=300, verbose_name='Ссылка на изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_flags', to='countries.Country')),
            ],
            options={
                'verbose_name': 'Флаг',
                'verbose_name_plural': 'Другие флаги',
            },
        ),
    ]
