# Generated by Django 3.0.12 on 2021-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0017_auto_20210228_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalflag',
            options={'verbose_name': 'Флаг', 'verbose_name_plural': 'Исторические флаги'},
        ),
        migrations.AddField(
            model_name='historicalflag',
            name='image_path',
            field=models.FilePathField(blank=True, path='/app/flags/media/historical-flags', recursive=True),
        ),
    ]
