# Generated by Django 3.0.12 on 2021-03-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0019_auto_20210302_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dl_imgs',
            field=models.BooleanField(default=False, verbose_name='Скачать картинки флагов'),
        ),
        migrations.AlterField(
            model_name='bordercountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='border_countries',
            field=models.ManyToManyField(blank=True, related_name='_country_border_countries_+', through='countries.BorderCountry', to='countries.Country', verbose_name='Соседние страны'),
        ),
        migrations.AlterUniqueTogether(
            name='bordercountry',
            unique_together={('country', 'border_country')},
        ),
    ]
