log:
  level: INFO
accessLog: {}
api:
  dashboard: true
  # insecure: true

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"
  
  # traefik:
  #   address: ":8080"
  

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "baikov52@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    dashboard:
      rule: "Host(`allflags.ru`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: api@internal
      middlewares:
        - csrf
        - auth
      tls:
        certResolver: letsencrypt

    media:
      rule: "Host(`allflags.ru`) && PathPrefix(`/media`)"
      # rule: "Host(`allflags.ru`)"
      # entryPoints:
      #   # - web
      #   - web-secure
        # - media
      middlewares:
        - csrf
      service: media
      tls:
        certResolver: letsencrypt

    web-secure-router:
      rule: "Host(`allflags.ru`) || Host(`www.allflags.ru`)"
      
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: media
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`allflags.ru`)"
      entryPoints:
        - flower
      service: flower
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
    
    auth:
      basicAuth:
        users:
          - "test:$apr1$IwjHZbRe$gXhMdI3EYhW2Npt7F6Jjs1"
          - "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    media:
      loadBalancer:
        servers:
          - url: http://nginx:80

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
